### PR TITLE
Db Config Fix (Part 3!)

### PR DESCRIPTION
**Pull request by TurtIeSocks**
- Accounts for how Extend handles arrays
- Function sets default (nest/portals for ManualDb and the rest for primary if none are specified)
- Should we add the sessions table in the customizable list?

### CODE REVIEW

**Review by versx — APPROVED** [review]

**Comment by versx** [comment]
Probably worth adding `session` table to the list tbh.

**Comment by TurtIeSocks** [comment]
@versx I tried to look into this a little bit but ran out of time:
https://github.com/mysqljs/mysql#poolcluster

From what I gathered, it sounds like we could setup a master and slave dbs, right? Since I'm basically running 2 full dbs with Chuck anyway, seems like a nice option for a little extra stability 👀

**Comment by versx** [comment]
> @versx I tried to look into this a little bit but ran out of time:
> https://github.com/mysqljs/mysql#poolcluster
> 
> From what I gathered, it sounds like we could setup a master and slave dbs, right? Since I'm basically running 2 full dbs with Chuck anyway, seems like a nice option for a little extra stability 👀

This is usually used for replication though, no? Replicating data from master to slave1 and slave2, etc. I think.

**Comment by TurtIeSocks** [comment]
> > @versx I tried to look into this a little bit but ran out of time:
> > https://github.com/mysqljs/mysql#poolcluster
> > From what I gathered, it sounds like we could setup a master and slave dbs, right? Since I'm basically running 2 full dbs with Chuck anyway, seems like a nice option for a little extra stability 👀
> 
> This is usually used for replication though, no? Replicating data from master to slave1 and slave2, etc. I think.

Oh probably.

**Comment by TurtIeSocks** [comment]
Lol oops. Did not mean to close. This is ready whenever. Been running in production for over a week.

**Review by versx — APPROVED** [review]

**Review by clburlison — APPROVED** [review]
works fine over here

**Pull request merged**
