### PR TITLE
Replace avatar clothing icon

### PR DESCRIPTION
**Pull request by shadowfox931**
Original icon looks out of place when filtering quests
image

### CODE REVIEW

**Review by clburlison — APPROVED** [review]

**Review by TurtIeSocks — APPROVED** [review]

**Comment by Mygod** [comment]
fUCK

**Comment by versx** [comment]
rippp

**Comment by Mygod** [comment]
it is not even a full cIRCLE

**Comment by shadowfox931** [comment]
> it is not even a full cIRCLE

Niantic didn't make it a full circle

**Comment by Mygod** [comment]
no you didn't make it a full circle

**Pull request merged**
