### PR TITLE
Support filtering quest pokemon by form

### PR DESCRIPTION
**Pull request by Mygod**
Needs testing.

### CODE REVIEW

**Review by TurtIeSocks — APPROVED** [review]

**Comment by Mygod** [comment]
This is my worst work yet.

**Review by clburlison — CHANGES_REQUESTED** [review]
I'm seeing some wonkyness with this PR. When I hide all and only show the Vulpix Alolan the pokestop doesn't actually appear on the map, can anyone else confirm? 

For testing purposes you can find a pokestop that has a Kanto Vulpix and change the quest_rewards to the alolan form:
```
Kanto
[{"type":7,"info":{"gender_id":0,"costume_id":0,"form_id":55,"shiny":false,"pokemon_id":37}}]

Alolan
[{"type":7,"info":{"gender_id":0,"costume_id":0,"form_id":46,"shiny":false,"pokemon_id":37}}]
``` 

Should we show the Alola icon in addition to the text?

Screen Shot 2020-10-15 at 11 06 42 PM

**Comment by Mygod** [comment]
@clburlison Alolan vulpix has form 56, not 46.

**Review by clburlison — APPROVED** [review]
MyGod is correct. I was just using the wrong form number. Works correctly.

**Comment by Mygod** [comment]
Just for the record, the normal form is there so that you will know whether the pokemon form/costume is generated upon claim:

* Squirtle (no form): https://www.reddit.com/r/thesilphroad/comments/jgzuh9/_/
* Sableye normal: https://www.reddit.com/r/thesilphroad/comments/jgzwhg/_/

**Pull request merged**
