### PR TITLE
Fix tooltip location

### PR DESCRIPTION
**Pull request by Mygod**
This patch is not working due to upstream issue: https://github.com/Leaflet/Leaflet/issues/6764

### CODE REVIEW

**Comment by versx** [comment]
Closing this for now until leaflet provides a solution.

**Comment by Mygod** [comment]
I think the fix is released in v1.7. Try update leaflet to v1.7.1 and merge this patch?

**Review by TurtIeSocks — APPROVED** [review]

**Comment by versx** [comment]
Good to merge?

**Comment by TurtIeSocks** [comment]
> Good to merge?

Yes. Just tweaked it slightly but everything is good to go.

**Review by versx — APPROVED** [review]

**Pull request merged**
