### PR TITLE
Bootswatch Theme API Support

### PR DESCRIPTION
**Pull request by versx**
TODO: 
- Save themes locally?

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

### CODE REVIEW

**Review by sketchysocks — COMMENTED** [review]
Is the resizing of the header an anticipated result?

Everything seems to work though, I think putting it somewhere in 'Settings' would be better. Or at the very least to the left of the Clear Cache button. It seems out of place currently.

**Review by Mygod — CHANGES_REQUESTED** [review]
In some themes:

* Top right banner buttons are not vertically centered. 
* The top bar also covers the map controls.
* Pokemon/Pokestop title uses the alternative text style but not Gym title. Also all other text still uses the old style (including font).
* Font used in filter menu is also inconsistent.
image
* Some theme does not differ red buttons and default buttons, e.g. Journal.
image
* Dropdown menu has incorrect text color sometimes.
image

Overall comment: I guess it is cool? Although I think the theme switch should be for server admin only. I do not think adding this feature is worth the maintenance efforts. (just look at number of bugs I found from my light testing)

**Review by clburlison — COMMENTED** [review]
No strong opinions either way... It works. Shetchy is a strong contender for best theme. I do think I'd rather this get hidden under the user settings.

**Comment by versx** [comment]
Closing in favor of #224

**Pull request closed without merging**
