### PR TITLE
Make weather timeout 62.5 minutes instead

### PR DESCRIPTION
**Pull request by Mygod**

### CODE REVIEW

**Review by versx — COMMENTED** [review]
Is this incase of delays from the server to the client of weather changes?

**Comment by Mygod** [comment]
Weather seems to be only updated every hour now. This is at least what we have been observing after the recent update.

**Comment by TurtIeSocks** [comment]
What about using something like Luxon to check if the weather has been scanned since the beginning of a new local hour? Instead of on a flat schedule. https://moment.github.io/luxon/

**Comment by Mygod** [comment]
Not sure if it is a good idea as it means that we need to implement all the edge cases in timezones exactly the same way as Niantic did. On the other hand, I think 62.5 min is a pretty good trade-off.

**Review by versx — APPROVED** [review]

**Review by TurtIeSocks — APPROVED** [review]

**Pull request merged**
