### PR TITLE
Landing/Home Page

### PR DESCRIPTION
**Pull request by versx**
Adds an optional home/landing page instead of just looping the login screen.
Credits to Anonymous and Alvadi for the two pages

### CODE REVIEW

**Comment by Mygod** [comment]
wtf is this home2

**Comment by versx** [comment]
> wtf is this home2

Secondary landing page I just need to get the updated one from Alvadi that has the login button. Need to make both `.example.mustache` files for people to choose from (or create their own).

**Comment by Mygod** [comment]
That cheap photoshop tho lol. Anyway I wouldn't recommend impersonating discord.

**Comment by versx** [comment]
> That cheap photoshop tho lol. Anyway I wouldn't recommend impersonating discord.

Yeah you're right

**Comment by clburlison** [comment]
I'm going to assume this is still a work in progress? Overall I really like the idea. Looks much better on mobile than desktop IMO. I can see users wanting to customize this screen quite a bit which leads to resurrecting #64 with the popup template support, or adding more config options for `home.mustache`:
- the background picture
- slash/title/main picture
- Title text
- body text

If you want help on moving this forward please let us know what direction you want to take.

**Comment by versx** [comment]
> I'm going to assume this is still a work in progress? Overall I really like the idea. Looks much better on mobile than desktop IMO. I can see users wanting to customize this screen quite a bit which leads to resurrecting #64 with the popup template support, or adding more config options for `home.mustache`:
> 
> * the background picture
> * slash/title/main picture
> * Title text
> * body text
> 
> If you want help on moving this forward please let us know what direction you want to take.

Kind of, just whipped it together real quick didn't put much customization into it. I also see people wanting to custom it with more options. Making it template-able would be ideal I think for allowing full customization. I'll try and get to the templates again this weekend.

**Comment by versx** [comment]
Please test and provide feedback.

**Comment by clburlison** [comment]
Everything is working for me in this PR. I made a few minor tweaks over in 309 to make it a bit more mobile friendly plus added a minor enhancement in 😅  We don't have the customization options added but at this point I think it might be a better idea to get this merged in and let more people use it, then add in the customizations afterwards.

**Review by TurtIeSocks — APPROVED** [review]

**Review by clburlison — APPROVED** [review]
Running this in prod over here. While it isn't perfect it's a nice improvement over the current behavior on master.

**Pull request merged**
