### PR TITLE
Ingress Portals

### PR DESCRIPTION
**Pull request by versx**
Adds support for showing Ingress portals via manualdb.
Adds support to search portals via global search.

Fix: #227 

Main Filter Menu:
image

Ingress Portals Filter Menu:
image

Preview: (Green for imported last 24 hours, Red for checked, Blue for last imported older than 24 hours)
image

Popup:
image

### CODE REVIEW

**Review by clburlison — CHANGES_REQUESTED** [review]
Basic functionally works + global search.
1. When portals are enabled and s2 cells (submissions cells) the portals should be the higher layer. The portal data is arguably more valuable than cell information when trying to determine new POI locations.

2. Filters > Reset & Disable all currently aren't hooked up

3. The 24hr filtering is not functioning for me.

4. Someone will ask for this to be viewable via a role in the future so might as well link it up now... 😓

**Comment by versx** [comment]
> Basic functionally works + global search.
> 
> 1. When portals are enabled and s2 cells (submissions cells) the portals should be the higher layer. The portal data is arguably more valuable than cell information when trying to determine new POI locations.
> 2. Filters > Reset & Disable all currently aren't hooked up
> 3. The 24hr filtering is not functioning for me.
> 4. Someone will ask for this to be viewable via a role in the future so might as well link it up now... 😓

Should all be fixed now.

**Comment by versx** [comment]
Was thinking since resizing the portal circles might not be the most useful, maybe replacing the M/XL option with a Configure button to give the user the option to show portals that are newer than x amount of hours. Giving them to the option to basically see portals made within the last 24, 48, 72, etc hours. Thoughts?

**Comment by clburlison** [comment]
Confirmed everything is functioning 100% now. The point I've been thinking about the most today was the implementation. It works but the more I think about it maybe this could be better if it uses the same UI from Spawnpoints.
Option 1: New portals (Last 24hrs)   On/Off
Option 2: All portals                            On/Off


Something about "Only New Portals (Last 24 Hours)" feels off for me...  

For the comment about configuring the "new" time period, it feels overkill. For Pogo the reason that ~24 hr valueable is because ingress gets the POI first then it is synced to Pogo. After 24hrs it's just another POI and it is possible to get import data from the popup. Maybe other community members/users can give some other insight?

**Comment by versx** [comment]
> Confirmed everything is functioning 100% now. The point I've been thinking about the most today was the implementation. It works but the more I think about it maybe this could be better if it uses the same UI from Spawnpoints.
> Option 1: New portals (Last 24hrs) On/Off
> Option 2: All portals On/Off
> 
> Something about "Only New Portals (Last 24 Hours)" feels off for me...
Adding an all filter seemed weird so instead I added 'Old Portals', this way they can see all old portals, all new portals, both, or none.
 
> For the comment about configuring the "new" time period, it feels overkill. For Pogo the reason that ~24 hr valueable is because ingress gets the POI first then it is synced to Pogo. After 24hrs it's just another POI and it is possible to get import data from the popup. Maybe other community members/users can give some other insight?
Gotcha that makes sense.

**Pull request merged**
