### PR TITLE
Update masterfile

### LINKED ISSUE #263: Cannot exclude stinky new form sableye
Upstream PR pending merge: https://github.com/WatWowMap/Masterfile-Generator/pull/4

### PR DESCRIPTION
**Pull request by Mygod**
Fix #263 hopefully.

### CODE REVIEW

**Review by TurtIeSocks — APPROVED** [review]
Fixes sableye issue.

**Comment by Mygod** [comment]
Rebased on latest master.

**Review by clburlison — CHANGES_REQUESTED** [review]
`static/js/index.js` has a few more unassigned variables from the maxPokemonId change.

Please apply the following `git apply /path/to/fixes.patch`

```diff
diff --git a/static/js/index.js b/static/js/index.js
index 04f6df0..650abaa 100644
--- a/static/js/index.js
+++ b/static/js/index.js
@@ -652,8 +652,7 @@ function loadStorage () {
         if (pokemonFilter['timers-verified'] === undefined) {
             pokemonFilter['timers-verified'] = { show: false, size: 'normal' };
         }
-        for (let i = 1; i <= maxPokemonId; i++) {
-            const pkmn = masterfile.pokemon[i];
+        for (const [i, pkmn] of Object.entries(masterfile.pokemon)) {
             const forms = Object.keys(pkmn.forms);
             for (let j = 0; j < forms.length; j++) {
                 const formId = forms[j];
@@ -7075,8 +7074,7 @@ function registerFilterButtonCallbacks() {
         // TODO: Default value
         defaultPokemonFilter['timers-verified'] = { show: false, size: 'normal' };
         let i;
-        for (i = 1; i <= maxPokemonId; i++) {
-            const pkmn = masterfile.pokemon[i];
+        for (const [i, pkmn] of Object.entries(masterfile.pokemon)) {
             const forms = Object.keys(pkmn.forms);
             for (let j = 0; j < forms.length; j++) {
                 const formId = forms[j];
@@ -7235,8 +7233,7 @@ function registerFilterButtonCallbacks() {
         // TODO: Default value
         defaultPokemonFilter['timers-verified'] = { show: false, size: 'normal' };
         let i;
-        for (i = 1; i <= maxPokemonId; i++) {
-            const pkmn = masterfile.pokemon[i];
+        for (const [i, pkmn] of Object.entries(masterfile.pokemon)) {
             const forms = Object.keys(pkmn.forms);
             for (let j = 0; j < forms.length; j++) {
                 const formId = forms[j];
```

**Review by clburlison — APPROVED** [review]
👍

**Pull request merged**
