### PR TITLE
Bug Fixes & Pokemon Popups

### PR DESCRIPTION
**Pull request by TurtIeSocks**
- Fix Sizing
- Timer button now toggles
- Fix Alolan/Galarian Filtering
- Fix Custom Filtering Buttons in Default.json
- Add Popup Customizing in user settings
- Modernize Pokemon Popups
- What popup info is displayed for weather and pokemon are customizable in default.json, more automatic adjusting coming soon.
- Touch up Rocket Popups

Screen Shot 2021-01-16 at 12 18 26 AM
Screen Shot 2021-01-16 at 12 18 39 AM
Screen Shot 2021-01-16 at 12 19 33 AM

**PVP % can be added if desired, along with swapping the icons for text names.**
Screen Shot 2021-01-16 at 12 20 30 AM
Screen Shot 2021-01-16 at 12 20 55 AM
Screen Shot 2021-01-16 at 12 21 10 AM
Screen Shot 2021-01-16 at 12 21 27 AM
Screen Shot 2021-01-16 at 10 51 26 AM

### CODE REVIEW

**Comment by Dewpg** [comment]
Working as intended.  Fixed Invasion/gym/raid/pokemon sizing that is ignored in master.  Popups indeed, modernized.

**Comment by TurtIeSocks** [comment]
Min Mode Added, customizable in config + user settings.
Screen Shot 2021-01-17 at 9 59 58 PM

Remove pvp stats if users don't care about them.
Screen Shot 2021-01-17 at 10 00 52 PM

**Comment by versx** [comment]
This PR has so much awesomeness going on in it, this needs to be merged asap once it's out of WIP. The only thing that stands out to me for some reason, is the IV size. Is it just me or is it just a _tad_ too big?

I'm super excited for the Pokemon type icons to be centered with the Pokemon again. 😅

**Review by versx — APPROVED** [review]

**Comment by TurtIeSocks** [comment]
> This PR has so much awesomeness going on in it, this needs to be merged asap once it's out of WIP. The only thing that stands out to me for some reason, is the IV size. Is it just me or is it just a _tad_ too big?
> 
> I'm super excited for the Pokemon type icons to be centered with the Pokemon again. 😅

The % or individual stats?

**Comment by versx** [comment]
> > This PR has so much awesomeness going on in it, this needs to be merged asap once it's out of WIP. The only thing that stands out to me for some reason, is the IV size. Is it just me or is it just a _tad_ too big?
> > I'm super excited for the Pokemon type icons to be centered with the Pokemon again. 😅
> 
> The % or individual stats?

I knew I should have said IV % specifically 😂

**Comment by clburlison** [comment]
This looks great. There is a merge conflict withe the `default.json` and it's currently marked as draft. Whenever you're ready for a final review I'll be happy to approve and get this merged. Fantastic updates.

**Comment by TurtIeSocks** [comment]
Screen Shot 2021-01-25 at 8 29 30 PM
Screen Shot 2021-01-25 at 8 31 39 PM

Gives the user the option to cut down if they're having display issues.

**Pull request merged**
